'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TANAPOP-PC\SQL2012SP1;Initial Catalog=MTL_MASTER_GUIDANCE;User ID=sa;"& _ 
            "Password=cps10mtl")>  _
        Public ReadOnly Property ConStr_Master() As String
            Get
                Return CType(Me("ConStr_Master"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TANAPOP-PC\SQL2012SP1;Initial Catalog=PTI_GUIDANCE_CARCOUNT_Project;Persist Security I"& _ 
            "nfo=False;User ID=sa;Password=cps10mtl")>  _
        Public ReadOnly Property ConnStrGuidance_RPT() As String
            Get
                Return CType(Me("ConnStrGuidance_RPT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TANAPOP-PC\SQL2012SP1;Initial Catalog=MTL_MASTER_GUIDANCE;Persist Sec"& _ 
            "urity Info=False;User ID=sa;Password=cps10mtl")>  _
        Public ReadOnly Property ConnStrMaster_RPT() As String
            Get
                Return CType(Me("ConnStrMaster_RPT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TANAPOP-PC\SQL2012SP1;Initial Catalog=PTI_GUIDANCE_CARCOUNT_Project;User ID=sa;Passwor"& _ 
            "d=cps10mtl")>  _
        Public ReadOnly Property ConStr_Guidance() As String
            Get
                Return CType(Me("ConStr_Guidance"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Debug_Mode() As Boolean
            Get
                Return CType(Me("Debug_Mode"),Boolean)
            End Get
            Set
                Me("Debug_Mode") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB.1;Persist Security Info=False;User ID=sa;Initial Catalog=MTL_MA"& _ 
            "STER_GUIDANCE;Data Source=TANAPOP-PC\SQL2012SP1;PWD=cps10mtl;")>  _
        Public ReadOnly Property ConnStrMaster() As String
            Get
                Return CType(Me("ConnStrMaster"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Provider=SQLOLEDB.1;Persist Security Info=False;User ID=sa;Initial Catalog=MTL_GU"& _ 
            "IDANCE;Data Source=TANAPOP-PC\SQL2012SP1;PWD=cps10mtl;")>  _
        Public ReadOnly Property ConnStrGuidance() As String
            Get
                Return CType(Me("ConnStrGuidance"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lime")>  _
        Public Property GREEN() As Global.System.Drawing.Color
            Get
                Return CType(Me("GREEN"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GREEN") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PTI_GUIDANCE_CARCOUNT_Project.My.MySettings
            Get
                Return Global.PTI_GUIDANCE_CARCOUNT_Project.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
